export const register = {
    REQUEST:'FETCH_REGISTER_REQUEST',
    RESPONSE:'FETCH_REGISTER_RESPONSE'
};
export const login = {
    REQUEST:'FETCH_LOGIN_REQUEST',
    RESPONSE:'FETCH_LOGIN_RESPONSE'
};
export const getHome = {
    REQUEST:'FETCH_GETHOME_REQUEST',
    RESPONSE:'FETCH_GETHOME_RESPONSE'
};
export const getLesson = {
    REQUEST:'FETCH_GETLESSON_REQUEST',
    RESPONSE:'FETCH_GETLESSON_RESPONSE'
};