export const register = {
    REQUEST:'FETCH_REGISTER_REQUEST',
    RESPONSE:'FETCH_REGISTER_RESPONSE'
};
export const login = {
    REQUEST:'FETCH_LOGIN_REQUEST',
    RESPONSE:'FETCH_LOGIN_RESPONSE'
};